# Generated by Django 5.2.4 on 2025-08-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_edited_message_messagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='messaging.message'),
        ),
    ]
