# Generated by Django 4.2.23 on 2025-07-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
