# Generated by Django 4.2.23 on 2025-07-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_id_conversation_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='user_id',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message_body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
