# Generated by Django 4.2.23 on 2025-07-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_rename_user_id_conversation_conversation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
    ]
